


###  Association analysis between somatic units and OS

```{r}



library(data.table)
library(dplyr)
library(magrittr)
library(survival)
library(qvalue)


# Read in the clinical file from your directory. 
cdr_clinical = fread("/data/ginny/tcga_pancan/important_files/primary_TCGA_CDR.tsv", stringsAsFactors = F)

# Set the gender variable.
acc_gender = T

# If your clinical data contains more than one cancer types, just keep the cancer of interest.
this_cdr = cdr_clinical %>%
dplyr::filter(type == "ACC")
 

# Set the variables used in the functions below 
this_barcode = this_cdr$bcr_patient_barcode
first_output_dir = paste0("/data/ginny/tcga_pancan/TCGA_all/ACC_somatic/")
second_output_dir = paste0(first_output_dir,"ACC_summarise_mutation_201901/")
this_piu_filename = paste0(second_output_dir,"piu_mapping_count.tsv")
this_bpiu_filename = paste0(second_output_dir, "bpiu_mapping_count.tsv")
this_npc_filename = paste0(second_output_dir, "npc_summarising_count.tsv")
third_dir = paste0(first_output_dir, "cox_test_201902/")


# Parameters details:
# race_group_min: the minimum number of people of the same race to be recognized as a race group. Patient belongs to a race group less than this number will be grouped to "Other".
# min_surv_days: the minimum number of days from follow up to the endpoint for the patient to be included to analysis. 
# min_surv_people: the minimum number of patients having an event for a survival model to be established. 
# patient_sum_min: the minimum number of patients having mutation in the unit of interest. 






#Build cox proportional hazard model for PIUs
univariate_cox_model_for_piu (piu_filename = this_piu_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "somatic",
                                                 output_dir = third_dir)


#Build cox proportional hazard model for bPIUs

univariate_cox_model_for_bpiu (bpiu_filename = this_bpiu_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "somatic",
                                                 output_dir = third_dir)

#Build cox proportional hazard model for nCUs

univariate_cox_model_for_npc (npc_filename = this_npc_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "somatic",
                                                 output_dir = third_dir)



```


### Association analysis between germline units and OS

```{r}


first_output_dir = paste0("/data/ginny/tcga_pancan/germline_raw_process/TCGA_all/ACC_germline/")
second_output_dir = paste0(first_output_dir,"ACC_summarise_mutation_201901/")
this_piu_filename = paste0(second_output_dir,"piu_mapping_count.tsv")
this_bpiu_filename = paste0(second_output_dir, "bpiu_mapping_count.tsv")
this_npc_filename = paste0(second_output_dir, "npc_summarising_count.tsv")
third_dir = paste0(first_output_dir, "cox_test_201902/")


#Build cox proportional hazard model for PIUs with germline mutaitons 

univariate_cox_model_for_piu (piu_filename = this_piu_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "germline",
                                                 output_dir = third_dir)


#Build cox proportional hazard model for bPIUs with germline mutations

univariate_cox_model_for_bpiu (bpiu_filename = this_bpiu_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "germline",
                                                 output_dir = third_dir)

#Build cox proportional hazard model for cCUs with germline mutations

univariate_cox_model_for_npc (npc_filename = this_npc_filename,
                                                 cdr_clinical = this_cdr,
                                                 gender_as_covariate = acc_gender,
                                                 race_group_min = 6,
                                                 min_surv_days = 90,
                                                 min_surv_people = 5,
                                                 patient_sum_min = 3,
                                                 mutation_type = "germline",
                                                 output_dir = third_dir)



```


### Association analysis for interaction between somatic and germline terms 


```{r}



somatic_univariate_output_dir =  paste0("/data/ginny/tcga_pancan/TCGA_all/ACC_somatic/cox_test_201902/")

somatic_dir = paste0("/data/ginny/tcga_pancan/TCGA_all/ACC_somatic/ACC_summarise_mutation_201901/")
germline_dir =  paste0("/data/ginny/tcga_pancan/germline_raw_process/TCGA_all/ACC_germline/ACC_summarise_mutation_201901/")

interaction_output_dir = paste0("/data/ginny/tcga_pancan/interaction_model/TCGA_all/ACC_interaction/all/")

this_univariate_somatic_piu_results_filename = paste0(somatic_univariate_output_dir, "somatic_piu_cdr_univariate_test.tsv")
this_univariate_somatic_bpiu_results_filename = paste0(somatic_univariate_output_dir, "somatic_bpiu_cdr_univariate_test.tsv")
this_univariate_somatic_npc_results_filename = paste0(somatic_univariate_output_dir, "somatic_npc_cdr_univariate_test.tsv")


this_somatic_piu_filename = paste0(somatic_dir, "piu_mapping_count.tsv")
this_somatic_bpiu_filename = paste0(somatic_dir, "bpiu_summarising_count.tsv")
this_somatic_npc_filename = paste0(somatic_dir, "npc_summarising_count.tsv")

this_germline_piu_filename = paste0(germline_dir, "piu_mapping_count.tsv")
this_germline_bpiu_filename = paste0(germline_dir, "bpiu_summarising_count.tsv")
this_germline_npc_filename = paste0(germline_dir, "npc_summarising_count_lim.tsv")


# Generate necessary files for interaction models
interaction_cox_model_for_somatic_units(
   univariate_somatic_piu_results = this_univariate_somatic_piu_results_filename,
  univariate_somatic_bpiu_results = this_univariate_somatic_bpiu_results_filename,
  univariate_somatic_npc_results = this_univariate_somatic_npc_results_filename,
  somatic_piu_filename = this_somatic_piu_filename,
  somatic_bpiu_filename = this_somatic_bpiu_filename,
  somatic_npc_filename = this_somatic_npc_filename,
  germline_piu_filename = this_germline_piu_filename,
  germline_bpiu_filename = this_germline_bpiu_filename,
  germline_npc_filename = this_germline_npc_filename,
  cdr_clinical = this_cdr,
  gender_as_covariate = acc_gender,
  race_group_min = 6,
  min_surv_days = 90,
  min_surv_people = 5,
  patient_sum_min = 5,
  mutation_type = "interaction",
  sig_level = 1,
  q_pvalue =quo(OS_count_pval),
  q_status = quo(OS),
  q_time = quo(OS.time),
  q_race = quo(os_race),
  v_status = "OS",
  v_time = "OS.time",
  v_race = "os_race",
  output_dir = interaction_output_dir)



 # This file to be read in is the output of the above function.
  info_name  = paste0("/data/ginny/tcga_pancan/interaction_model/TCGA_all/ACC_interaction/all/OS_somatic_sig_unit_survival_info.tsv")
  
  info_data = fread(info_name,
                    stringsAsFactors = F)
  
# Fit cox proportional models with the interaction terms. 
fit_survival_model_interaction_coeff_test(
  surv_info_data = info_data,
  germline_need_filename = paste0("/data/ginny/tcga_pancan/interaction_model/TCGA_all/ACC_interaction/all/OS_need_germline_counts.tsv"),
  min_surv_days = 90,
  min_surv_people = 5,
  q_status = quo(OS),
  q_time = quo(OS.time),
  q_race = quo(os_race),
  v_status = "OS",
  v_time = "OS.time",
  v_race = "os_race",
  output_dir = paste0("/data/ginny/tcga_pancan/interaction_model/TCGA_all/ACC_interaction/test/"),
  output_coeff_name = "interaction_model_result_test.tsv")



```











