# 
# library(data.table)
# library(dplyr)
# library(magrittr)

#' Extract germline mutations annotated by the snpEff tool for a cancer type of your interest.
#' 
#' This function generates two files as the final products. First, mutations which result in protein-consequence with
#' effect on proteins annotated; Second, mutations without protein-consequence.
#' 
#' @param mc3_info_file File name of the mc3 somatic variants from TCGA. 
#' @param cancer_type TCGA cancer type identifier, e.g. STAD, BRCA. 
#' @param sample_cn_id A barcode codebook provided by the packge.
#' @param output_dir The directory you would like to have your output files in.
#' @import dplyr magrittr data.table
#' @export
#' @details 
#' @examples 
#' somatic_extraction_annotation_pos(mc3_info_file = "/data/ginny/tcga_pancan/important_files/mc3_info.tsv" ,
#'                                  cancer_type = "STAD",
#'                                  cancer_barcode = stad_barcode,
#'                                  output_dir = "/data/ginny/tcga_pancan/STAD_somatic/")



somatic_extraction_annotation_pos = function(mc3_info_file,
                                             cancer_type,
                                             cancer_barcode,
                                             output_dir)
{
  
  select_cancer_mc3(mc3_filename = mc3_info_file ,
                    cancer_barcode = cancer_barcode,
                    output_dir = output_dir,
                    output_name = paste0(cancer_type,"_somatic_mc3.tsv"))
  cat("1/3...somatic variants for this cancer type selected.","\n")
  
  
  this_mc3_name = paste0(output_dir, cancer_type, "_somatic_mc3.tsv")
  
  divide_somatic_to_pc_npc(mc3_data_name = this_mc3_name,
                           output_dir = output_dir,
                           pc_output_name = paste0(cancer_type, "_somatic_mc3_pc.tsv"),
                           npc_output_name = paste0(cancer_type, "_somatic_mc3_npc.tsv"))
  cat("2/3...somatic variants divided to PC and nPC parts.","\n")
  
  
  this_pc_name = paste0(output_dir, cancer_type, "_somatic_mc3_pc.tsv")
  
  annotate_mc3_pc_position_info(pc_data_name = this_pc_name,
                                output_dir = output_dir,
                                output_name = paste0(cancer_type, "_somatic_mc3_pc_pos.tsv"))

  cat("3/3...protein positions for PC variants annotated.","\n")
  
  cat("Somatic variants extraction and annotation finished!","\n")
  

}


### somatic mapping

## I will add whole gene count here.


#' Map soamtic pc to piu and bpiu, summarise bpiu and npc per gene
#' 
#' This function generates three files as the final products. First, each piu mapped, second, bpiu summarised per gene, third, 
#' npc summarised per gene.
#' 
#' @param ptm_pfam_filename  The file provided by the package where the piu information is recorded.
#' @param pc_data_name the file listing mutations that result in protein consequence. A file generated by function germline_extraction_annotation_pos
#' @param npc_data_name the file listing mutations that result in non-protein consequence. A file generated by function germline_extraction_annotation_pos
#' @param cancer_barcode TCGA barcodes for this cancer type cohort.
#' @param locus_level_mut_min This minimum frequency for selecting mutations on locus level.
#' @param output_dir The directory you would like to have your output files in.
#' @import dplyr magrittr data.table
#' @export
#' @details 
#' @examples 
#' somatic_piu_mapping (ptm_pfam_filename =  "/data/ginny/tcga_pancan/important_files/ptm_domain_combine_df.tsv",
#'                      pc_data_name  = 
#'                        "/data/ginny/tcga_pancan/germline_raw_process/STAD_snpeff_annotation/snpeff_variant_anno_pc_pos.tsv",
#'                      npc_data_name = 
#'                        "/data/ginny/tcga_pancan/germline_raw_process/STAD_snpeff_annotation/snpeff_variant_anno_npc.tsv",
#'                      cancer_barcode = stad_barcode,
#'                      sample_cn_id = sample_cn_id,
#"                      output_dir = "/data/ginny/tcga_pancan/germline_raw_process/STAD_summarise_mutation/")

somatic_piu_mapping = function (ptm_pfam_filename,
                                 pc_data_name,
                                 npc_data_name,
                                 cancer_barcode,
                                 locus_level_mut_min = 3,
                                 gene_level_mut_min = 1,
                                 output_dir)
  
{
  
  
  # ptm_domain_filename = "/data/ginny/tcga_pancan/important_files/ptm_domain_combine_df.tsv"
  # pc_data_name = "/data/ginny/tcga_pancan/TCGA_all/BRCA_somatic/BRCA_somatic_mc3_pc_pos.tsv"
  # npc_data_name = "/data/ginny/tcga_pancan/TCGA_all/BRCA_somatic/BRCA_somatic_mc3_npc.tsv"
  # cancer_barcode = brca_barcode
  # locus_level_mut_min = 3
  # gene_level_mut_min = 1
  # output_dir = "/data/ginny/tcga_pancan/TCGA_all/BRCA_somatic/test/"
  # 
  
  
  locus_level_matrix (
    pc_data_name = pc_data_name,
    cancer_barcode = cancer_barcode,
    mut_freq_min = locus_level_mut_min,
    output_dir = output_dir,
    output_filename = "mc3_count_matrix.tsv")
  
  if(file.exists(paste0(output_dir,"mc3_count_matrix.tsv")))
  {
    cat("1/4...locus level count matrix generated.","\n")
    
  }else{
    cat("1/4...proceed to gene level mapping.","\n")
  }
  
  
  
  
  gene_level_matrix (
    pc_data_name = pc_data_name,
    cancer_barcode = cancer_barcode,
    mut_freq_min = gene_level_mut_min,
    output_dir = output_dir,
    output_filename = "gene_level_count_matrix.tsv")
  
  
  if(file.exists(paste0(output_dir,"gene_level_count_matrix.tsv")))
  {
    cat("2/4...gene level count matrix generated.","\n")
    
  }else{
    cat("2/4...proceed to PIU mapping.","\n")
  }
  
  
  
  mc3_map_uni_piu (ptm_pfam_filename = ptm_pfam_filename,
                             pc_data_name = pc_data_name,
                             cancer_barcode = cancer_barcode,
                             output_dir = output_dir,
                             piu_output_filename = "piu_mapping_count.tsv",
                             bpiu_output_filename = "bpiu_summarising_count.tsv")
  
  if(file.exists(paste0(output_dir,"piu_mapping_count.tsv")))
  {
    cat("3/4...PIU and bPIU count matrices generated.","\n")
    
  }else{
    cat("3/4...proceed to nPC mapping.","\n")
  }
  

  
  mc3_map_npc (npc_data_name = npc_data_name,
                          cancer_barcode = cancer_barcode,
                          output_dir = output_dir,
                          output_filename = "npc_summarising_count.tsv")
  
  
  if(file.exists(paste0(output_dir,"npc_summarising_count.tsv")))
  {
    cat("4/4...nPC count matrix generated.","\n")
    
    
  }else{
    cat("4/4.. no nPC mapped.","\n")
  }
  
  
  
  
  cat("Somatic PIU mapping finished!", "\n")
  
  
}
  
  
  
  
  
  ## ok now do it for the somatic part 
  
  
  
  
  

